title = "Fader Homepage 2018"
baseURL = "https://new-homepage-2018.netlify.com/"
languageCode = "en-us"
theme = "airspace-hugo"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
canonifyURLs = true
laxHtmlBlocks = true

[menu]

  [[menu.header]]
    weight = 2
    name = "About"
    url = "/about"
  [[menu.header]]
    weight = 2
    name = "Portfolio"
    url = "/work"
  [[menu.header]]
    weight = 3
    name = "Blog"
    url = "/blog"
  # [[menu.header]]
  #   weight = 4
  #   name = "Service"
  #   url = "/service"
  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "About"
    url = "/about"
  [[menu.footer]]
    weight = 2
    name = "Contact"
    url = "/contact"
  [[menu.footer]]
    weight = 3
    name = "How it works"
    url = "#"
  [[menu.footer]]
    weight = 4
    name = "Blog"
    url = "#"
  [[menu.footer]]
    weight = 5
    name = "Contact"
    url = "/contact"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2016"

  # home = "Fader Home"

  [params.slider]
    enable = true
    title = "Visualising Dance Music"
    subtitle = "A Festival is More than Meets the Eye<br/> Createing Amazing Experiences Around The World <br/><br/>[↓](#intro)"

  [params.wrapper]
    enable = true
    title = "Meet Fader"
    italic = "James (Fader) Cui is a talented multi-media artist and VJ specializing in Stage Design, software development and Video Mapping. <br><br>Over the past decade, Fader has contributed to many big festivals such as Coachella, Burning Man, Insomniac, Fuji Rock, Mapping Festival, Backwoods and Intro Music Festival."
    paragraph = "After a degree in Illustration from the Art Center College of Design (USA), he continued to explore programming code for his audio-video performances. In 2015, he received the App Art Award from ZKM for [EDMT](https://goo.gl/GqTFRM), an app that allows  you to generate graphics and EDM inspired sounds with your phone or tablet. <br><br> In 2004, he founded [Neuromixer](https://neuromixer.com/) to release AVmixer, a line of VJ software for live performances. In 2017 he established [AVloops](http://www.avloops.com), a video content marketplace platform for VJ related animations and loops. <br><br>At the moment, while busy with the role of CEO, he continues to freelance as a VJ and stage designer to share with people his passion for audiovisual. Additionally, he’s been teaching video mapping, Processing and Unity 3D to like-minded artists."
  [params.wrapper.button]
      caption = "Read More"
      url = "/about"

  [params.blog]
    enable = true
    title = "Latest news from Fader"
    subtitle = "Catch up with Fader, anytime and anywhere"

  [params.feature]
    enable = true
    title = "Every show delivers a visual impact to the audience"
    content = "The stage can be considered as a fine-art sculpture in the hands of an experienced the designer, Fader shapes his vision according to the type of event and audience. The stage can be modern or classic. Regardless of outdoor or indoor, the LED screens, projectors, lasers and lights become the building blocks to a masterpiece."
  [params.feature.button]
      caption = "View More"
      url = "/work"

  [params.call]
    enable = true
    title = "Together, we will create the most memorable show!"
    paragraph = "Every show take an entire team, with extensive planning and execution comes a great show that will stay in the audiences' memories for a long long time."

  [params.contact]
    enable = true
    title = "Get in Touch"
    subtitle = "If you have an upcoming project or questions about my past work, feel free to write."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Contact"
      address = "Berlin, Germany"
      email = "Email: vjfader@mail.com"
      phone = "Phone: +49 17680551258‬"
    [params.contact.gmaps]
      title = "Where in the World?"
